call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'tmhedberg/matchit'
Plug 'tpope/vim-surround'

Plug 'Valloric/YouCompleteMe', {'do':'./install.py --clang-completer'}
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'mattn/emmet-vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'scrooloose/syntastic'
Plug 'airblade/vim-gitgutter'
Plug 'tomtom/tcomment_vim'

"For Javscript
Plug 'prettier/vim-prettier', { 'do': 'npm install' }


"Plug 'gcorne/vim-sass-lint'


"For Colors
Plug 'lifepillar/vim-solarized8'
"Plug 'vim-airline/vim-airline'

call plug#end()

source ~/.vim/startup/settings.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/compileAndRun.vim
source ~/.vim/startup/pluginSettings.vim
